### ISSUE TITLE
Credit the original author

### ISSUE THREAD

**Issue by profi200** [Cpasjuste/SafeSysUpdater#1]
Just wanted to point out you should give at least proper credit to the original authors of the sw instead of making a new repo ~~and claiming it's yours~~.

And it would be better making a fork or using git submodules.

**Comment by Cpasjuste** [comment]
What are you saying ? Where does i claim it's mine ?
- gbatemp release thread clearly state that this is a fork of sysupdater : https://gbatemp.net/threads/wip-safesysupdater.409392/ (this is the first line of the post).
- the first screen you see on the application does also give proper credits (screenshots on gbatemp) : https://gbatemp.net/threads/wip-safesysupdater.409392/
- the github project comment is "3DS sysupdater mod"

Else i never worked with submodule and i didn't want to. I know this crappy guy try to fuck me in any possible way, but believe me, i'm doing this since a while now and never had any problem, all credits are always where they belong.

I hope you'll explain the problem in detail.

**Comment by profi200** [comment]
I missed the credit on the startup screen i admit. But credits in a README and/or where you post your releases would be great too. You edited the release post so that's fine.

Would just be nice now if you could either make it a fork or use git submodules.

**Comment by d4mation** [comment]
Generally for something like this, it would make more sense to Fork the original project.

This way it is clear where your project branches off from the original [SysUpdater](https://github.com/profi200/sysUpdater) repository and then if @profi200 were to make new Commits, it would say how far ahead/behind your Fork is from the Original.

It also prevents issues about ownership from cropping up.

Edit: [List of SysUpdater Forks on GitHub](https://github.com/profi200/sysUpdater/network)

**Comment by mariogamer2** [comment]
5998805f4d4393b1536743d1db815e2fa27144cf  on my repo fix this

**Comment by Cpasjuste** [comment]
Well, now SafeSysUpdater has only the name left from SysUpdater as I removed all the original SysUpdayer code (was too lazy to write the 2-3 title installation/deletion functions needed before but as I don't like how this people are I've done it) . So I'll also remove the credits to this author (@profi200).
