### ISSUE TITLE
build issues...

### ISSUE THREAD

**Issue by mariogamer2** [Cpasjuste/SafeSysUpdater#9]
Since 040bb9ccc512554ea745e14bb275650ebc9485d2 I receive build error.

I will copy the log soon.

Maybe SuperUserLib have to be included in the makefile.Don't know as I'm a noob and don't have time for this now :(

Also,it's not makefile,but it's cmakelist,and I don't know at all how to add it :-1:

**Comment by kitlith** [comment]
Well, it _should_ work the same as before the PR, because you just replaced the folder with a submodule, which acts as a folder. Now, if it didn't build before the PR, then I would go looking at 'was it added to the CMakeLists?'

Probably the best way to figure it out is via an error log. And I can't test myself, because my desktop isn't fixed yet. Soooo... ._.

**Comment by mariogamer2** [comment]
Log:

CMake:

http://pastebin.com/ACGMq7Dk

make:

http://pastebin.com/bqw2Uej4
